# Default values for k8s-mutating-admission-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: udhos/k8s-mutating-admission-webhook
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# redeploy:
#
# 'always': adds a random annotation to Deployment in
#           order to redeploy the pods whenever the chart is reapplied.
#
# 'reconfig': adds annotations with checksums of configurations in
#             order to redeploy the pods whenever configuration is changed.
#
# https://v3.helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
#
redeploy: always

priorityClassName: system-node-critical

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

podHealthCheck:
  port: 8443
  path: /health
  scheme: HTTPS

# add custom labels to deployment pods
customLabels:
  app: k8s-mutating-admission-webhook

resources:
  requests:
    cpu: 100m
    memory: 300Mi
    ephemeral-storage: 200Mi
  limits:
    cpu: 2000m
    memory: 300Mi
    ephemeral-storage: 200Mi

# Currently autoscaling is NOT supported.
# The webhook must have only one pod running at a time.
# A second pod would replace the certificate injected in the webhook by the first pod.
autoscaling:
  enabled: false # DO NOT turn on autoscaling
  minReplicas: 1
  maxReplicas: 30
  targetCPUUtilizationPercentage: 80
  apiVersion: autoscaling/v2

nodeSelector: {}

tolerations: []

affinity: {}

#
# See: https://stackoverflow.com/questions/72816925/helm-templating-in-configmap-for-values-yaml
#
configMapProperties:
  DEBUG: "true"
  RULES: /etc/webhook/rules.yaml
  #ADDR: ":8443"
  #ROUTE: "/mutate"
  #HEALTH: "/health"
  #NAMESPACE: "webhook"
  #SERVICE: "k8s-mutating-admission-webhook"
  #WEBHOOK_CONFIG_NAME: "udhos.github.io"
  #NAMESPACE_EXCLUDE_LABEL: "webhook"
  #
  # Ignore: means that an error calling the webhook is ignored and the API request is allowed to continue.
  # Fail: means that an error calling the webhook causes the admission to fail and the API request to be rejected.
  #FAILURE_POLICY: "Ignore"
  #
  #REINVOCATION_POLICY: "IfNeeded"
  #IGNORE_NAMESPACES: "karpenter"            # space-separated list of namespaces
  #ACCEPT_NODE_SELECTORS: "kubernetes.io/os" # space-separated list of nodeSelectors

configDir:
  rules.yaml: |
    # these fields match with regexp.
    # be careful about using them as literals,
    # since the expression "key" matches "my-key1".
    #
    # restrict_tolerations[].toleration.key
    # restrict_tolerations[].toleration.operator
    # restrict_tolerations[].toleration.value
    # restrict_tolerations[].toleration.effect
    # restrict_tolerations[].allowed_pods.namespace
    # restrict_tolerations[].allowed_pods.name
    # place_pods[].pod.namespace
    # place_pods[].pod.name

    restrict_tolerations:

      # if a toleration is unmatched, it is allowed for all PODs.
      # if a toleration is matched, only matched PODs can have it.
      #
      # the empty expression matches anything.
      # the underscore (_) in the beginning of the expression negates it.
      # "" matches anything.
      # "_" negates the empty string, hence it matches nothing.

      # remove key1 from any pod
      - toleration:
          # exactly match key1 regardless of other fields
          key: ^key1$    # exact match
          #operator: ""  # empty string matches anything
          #value: ""     # empty string matches anything
          #effect: ""    # empty string matches anything
        allowed_pods:
          # match NO pod
          - namespace: _ # negated empty string matches nothing
            name: _      # negated empty string matches nothing

      # remove exactly Exists from all pods except pods prefixed with "^daemonset-"
      - toleration:
          # match exactly Exists
          key: ^$             # match only the empty string
          operator: ^Exists$  # exact match
          value: ^$           # match only the empty string
          effect: ^$          # match only the empty string
        allowed_pods:
          # match only POD prefixed as daemonset-
          - #namespace: ""    # empty string matches anything
            name: ^daemonset- # match prefix
    
    # if the pod matches multiple place_pods rules,
    # it will receive tolerations and node_selectors
    # from ALL matches.

    place_pods:
      - pod:
          labels:
            color: red
        add:
          node_selector:
            node: alpha
      - pod:
          # match only POD prefixed as coredns-
          #namespace: ""    # empty string matches anything
          name: ^coredns-   # match prefix
        add:
          tolerations:
            - key: key1
              operator: Equal
              value: value1
              effect: NoSchedule
            - key: key2
              operator: Equal
              value: value2
              effect: NoSchedule
          node_selector:
            key1: value1
            key2: value2
