apiVersion: v1
kind: Service
metadata:
  name: k8s-mutating-admission-webhook
  labels:
    {{- include "k8s-mutating-admission-webhook.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    {{- include "k8s-mutating-admission-webhook.selectorLabels" . | nindent 4 }}
